AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - spec/**/*
  NewCops: enable
  SuggestExtensions: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 90

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceBeforeBrackets:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Metrics/ClassLength:
  Max: 130

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 130

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/OptionalArguments:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
